### ISSUE TITLE
Fork mi-cho-coq

### ISSUE THREAD

**Issue by sbihel** [spruceid/did-tezos#23]
Currently to run a proof in mi-cho-coq needs to be in the repo. So we need to fork it, and eventually it might be merged as an example or test. But we will need to keep the fork as some kind of audit proof.

@wyc would it be possible to fork https://gitlab.com/nomadic-labs/mi-cho-coq?

**Comment by wyc** [comment]
@sbihel you should have access to https://github.com/spruceid/mi-cho-coq
